spring:
  application:
    name: sagopalgo

  datasource:
    url: jdbc:mysql://localhost:3306/sagopalgo
    username: *
    password: *
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret:
    key: *
  access-token:
    expiration:
      access-token: 1800000 # 30 minutes
      refresh-token: 1209600000 # 14 days

